name: Continuous Integration

on:
  pull_request:

jobs:
  CI_Ubuntu:
    name: Ubuntu_${{ matrix.configuration }}_x64
    runs-on: ubuntu-latest
    container:
      image: novelrt/novelrt-build:latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run CI Build Script
        run: scripts/cibuild.sh --configuration ${{ matrix.configuration }}

  CI_Windows:
    name: Windows_${{ matrix.configuration }}_x64
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Windows Setup
        run: scripts/machine-setup.cmd

      - name: Run CI Build Script
        run: scripts/cibuild.cmd -configuration ${{ matrix.configuration }}

      - name: Check Formatting
        id: formatting
        run: scripts/ci-check-format.cmd ${{ matrix.configuration }}
        if: ${{ steps.build.outcome == 'success' }}

      - name: Generate Formatting Patch
        id: generate-clang-format-patch
        run: scripts/ci-generate-diff.cmd
        if: ${{ steps.formatting.outcome == 'failure' }}

      - name: Upload Patch
        uses: actions/upload-artifact@v1
        if: ${{ steps.generate-clang-format-patch.outcome == 'success' }}
        with:
          name: clang-format.patch
          path: clang-format.patch
